name: Render and Deploy Docs

on: [push]

jobs:
  build:
    name: Render and deploy protocol and API docs
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Install dependencies and credentials
      - name: Load Rust caching
        uses: Swatinem/rust-cache@v1
      - name: Load get-version action to grab version component of deployment path
        uses: battila7/get-version-action@v2
        id: get_version
      - name: Install mdbook
        run: |
          cargo install mdbook mdbook-katex mdbook-mermaid
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}

      # Build artifacts
      - name: Build API docs
        run: |
          cargo doc --no-deps -p decaf377
          cargo doc --no-deps -p tower-abci
          cargo doc --no-deps
          # This is useful until ABCI changes are merged upstream
          # https://github.com/informalsystems/tendermint-rs/pull/862
          cargo doc --no-deps -p tendermint
      - name: Build protocol docs
        run: |
          mdbook build

      # Deploy to S3
      - name: Move docs to subdirectories
        run: |
          if [ -d "s3-tmp" ]; then rm -rf s3-tmp; fi
          mkdir s3-tmp
          mv target/doc s3-tmp/api
          mv book s3-tmp/book
      - name: Sync to S3
        run: aws s3 sync s3-temp/* s3://${{ secrets.S3_BUCKET_NAME }}/${{ env.GITHUB_REF }} --delete
